version: '3.8'

services:

  php:
    container_name: symfony-component-generator-php
    build:
      context: .
      target: production
      args:
        DOCKER_BUILDKIT: 1
      dockerfile: docker/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - .:/app/