version: '3.8'

services:

  php:
    container_name: ds-data-php
    build:
      context: .
      target: development
      args:
        DOCKER_BUILDKIT: 1
      dockerfile: docker/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app/