name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/php/Dockerfile --target=production --tag symfony-component-generator:$(date +%s)
    - name: Composer dependencies install
      run: composer install
    - name: PHPStan
      run: ./vendor/bin/phpstan analyse src
    - name: PHPCodeSniffer
      run: ./vendor/bin/phpcs --standard=PSR12 src
    - name: PHPUnit tests
      run: ./vendor/bin/phpunit

