name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: symfony-component-generator-php-image:latest
          file: docker/php/Dockerfile
          target: production
          outputs: type=docker,dest=/tmp/symfony-component-generator-php-image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: symfony-component-generator-php-image
          path: /tmp/symfony-component-generator-php-image.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: symfony-component-generator-php-image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/symfony-component-generator-php-image.tar
          docker image ls -a
          docker run -d --name symfony-component-generator-php -it symfony-component-generator-php-image 
          docker container ls -a
      - name: Composer dependencies install
        run: docker exec symfony-component-generator-php composer install
      - name: Executing tests
        run: docker exec symfony-component-generator-php sh execute-tests.sh